<%@ Page Title="" Language="C#" MasterPageFile="~/View/Users/UserMaster.Master" AutoEventWireup="true" CodeBehind="Booking.aspx.cs" Inherits="EHotelMS.View.Users.Booking" EnableEventValidation="false" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MyBody" runat="server">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <div class="mb-3">
                                    <label for="RoomTb" class="form-label">Room name</label>
                                    <input type="text" placeholder="Select a room" class="form-control" id="RoomTb" runat="server" readonly required>
                                </div>
                                <div class="mb-3">
                                    <label for="DateInTb" class="form-label">Check in</label>
                                    <input type="date" class="form-control" id="DateInTb" runat="server" required>
                                </div>

                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label for="AmountTb" class="form-label">Cost(1 Day)</label>
                                    <input type="text" class="form-control" id="AmountTb" runat="server" readonly required>
                                </div>
                                <div class="mb-3">
                                    <label for="DateOutTb" class="form-label">Check out</label>
                                    <input type="date" class="form-control" id="DateOutTb" runat="server" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col d-grid">
                                <asp:Button ID="ResetBtn" runat="server" Text="Reset" class="btn btn-danger" />
                            </div>
                            <div class="col d-grid">
                                <asp:Button ID="SaveBtn" runat="server" Text="Book" class="btn btn-success" OnClick="SaveBtn_Click" />
                            </div>
                            <label id="ErrMsg" runat="server" class="text-danger"></label>
                        </div>
                    </div>
                </div>
                <h3 class="text-primary">Rooms Information</h3>
                <asp:GridView ID="RoomGV" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" Width="100%" BorderStyle="Solid" BorderWidth="2px" BorderColor="#41A666" OnSelectedIndexChanged="RoomGV_SelectedIndexChanged">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:TemplateField ShowHeader="False">
                            <ItemTemplate>
                                <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="False" CommandName="Select" Text="Select"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#7C6F57" />
                    <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#41a666" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#E3EAEB" />
                    <SelectedRowStyle BorderStyle="Solid" BorderWidth="2px" BorderColor="#042611" Font-Bold="True" ForeColor="#333333" BackColor="lightgray" />
                    <SortedAscendingCellStyle BackColor="#F8FAFA" />
                    <SortedAscendingHeaderStyle BackColor="#246B61" />
                    <SortedDescendingCellStyle BackColor="#D4DFE1" />
                    <SortedDescendingHeaderStyle BackColor="#15524A" />
                </asp:GridView>
            </div>
            <div class="col">
                <div class="row">
                    <div class="col"></div>
                    <div class="col">
                        <h2 class="text-primary">Your Book orders</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <asp:GridView ID="BookingGV" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" Width="100%" BorderStyle="Solid" BorderWidth="2px" BorderColor="#41A666" AutoGenerateDeleteButton="True" OnSelectedIndexChanged="BookingGV_SelectedIndexChanged">
                            <AlternatingRowStyle BackColor="White" />
                            <EditRowStyle BackColor="#7C6F57" />
                            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#41a666" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#E3EAEB" />
                            <SelectedRowStyle BorderStyle="Solid" BorderWidth="2px" BorderColor="#042611" Font-Bold="True" ForeColor="#333333" BackColor="lightgray" />
                            <SortedAscendingCellStyle BackColor="#F8FAFA" />
                            <SortedAscendingHeaderStyle BackColor="#246B61" />
                            <SortedDescendingCellStyle BackColor="#D4DFE1" />
                            <SortedDescendingHeaderStyle BackColor="#15524A" />
                        </asp:GridView>
                    </div>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
